apiVersion: v1
kind: Service
metadata:
  name: delivery-postgres
spec:
  ports:
    - port: 5432
  selector:
    app: delivery-postgres
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: delivery-postgres
spec:
  serviceName: "delivery-postgres"
  replicas: 1
  selector:
    matchLabels:
      app: delivery-postgres
  template:
    metadata:
      labels:
        app: delivery-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:15
          env:
            - name: POSTGRES_USER
              value: myuser
            - name: POSTGRES_PASSWORD
              value: mypassword
            - name: POSTGRES_DB
              value: delivery_db
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
  volumeClaimTemplates:
    - metadata:
        name: postgres-storage
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
