apiVersion: v1
kind: Secret
metadata:
  name: secrets
type: Opaque
stringData:
  database_url: postgresql+asyncpg://myuser:mypassword@delivery-postgres:5432/delivery_db
  shipengine_api_key: TEST_R1rw7s4qEDSi87gSQKPlHj5xJK38+HTaaRE0JCRc4S0
  shipengine_carrier_id: se-2651789